### ISSUE TITLE
Lock dockerfile on a specific alpine version

### ISSUE THREAD

**Issue by pensiero** [mjuenema/docker-alpine-supervisor#1]
@mjuenema don't you think could be better to specify an Alpine version, in order to be sure that with future releases it won't break?

In case, I can provide a PR.

Thanks

**Comment by mjuenema** [comment]
Any help is very welcome. Please submit a PR but it might take a few days as I am currently on holidays.

**Comment by pensiero** [comment]
Done :) Please test with your environment, in mine is working fine

**Comment by mjuenema** [comment]
Thanks. I am currently overseas on holidays and won't be able to test this until late in January. Markus

**Comment by pensiero** [comment]
No problem :)
